import json
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import pandas as pd
import streamlit as st

from src.engine import get_chat_engine
from src.model_loader import (
    get_embedding_model,
    initialise_llm,
)
from src.sql_engine import (
    answer_sql_question,
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Treasoria",
    page_icon="💎",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# ACTIVE COMPANY
# ============================================================

COMPANY_PROFILE_PATH = Path(
    "data/company_profile.json"
)

COMPANY_NAME = "Code & Coffee GmbH"
COMPANY_OWNER = "Blue Jesus"
COMPANY_ADDRESS = "Ravensberger Str. 22"
COMPANY_CITY = "33602 Bielefeld, Germany"
COMPANY_SECTOR = "International Café & Gastronomy"
COMPANY_STATUS = "Synthetic business identity"

DEFAULT_COMPANY = {
    "company_id": "code_and_coffee",
    "name": COMPANY_NAME,
    "owner": COMPANY_OWNER,
    "address": COMPANY_ADDRESS,
    "city": COMPANY_CITY,
    "sector": COMPANY_SECTOR,
    "status": COMPANY_STATUS,
    "last_updated": "never",
}


def _now_berlin() -> str:
    """
    Return the current local time for Bielefeld.
    """

    return datetime.now(
        ZoneInfo("Europe/Berlin")
    ).strftime(
        "%Y-%m-%d %H:%M"
    )


def load_company() -> dict:
    """
    Load the saved company profile.
    """

    profile = DEFAULT_COMPANY.copy()

    if COMPANY_PROFILE_PATH.exists():

        with open(
            COMPANY_PROFILE_PATH,
            "r",
            encoding="utf-8",
        ) as file:

            saved = json.load(file)

        profile.update(saved)

    return profile


def save_company(
    profile: dict,
) -> None:
    """
    Save the active company profile.
    """

    profile["last_updated"] = (
        _now_berlin()
    )

    COMPANY_PROFILE_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        COMPANY_PROFILE_PATH,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            profile,
            file,
            ensure_ascii=False,
            indent=2,
        )


if "company_profile" not in st.session_state:

    st.session_state.company_profile = (
        load_company()
    )


ACTIVE_COMPANY = (
    st.session_state.company_profile
)


# ============================================================
# DATASET LOCATION
# ============================================================

def _find_dataset_dir() -> Path | None:
    """
    Locate the Treasoria structured dataset.
    """

    project_root = (
        Path(__file__).parent
    )

    data_path = (
        project_root
        / "data"
    )

    dataset_directories = [
        directory
        for directory
        in data_path.glob(
            "Treasoria_Datasets*"
        )
        if directory.is_dir()
    ]

    return (
        dataset_directories[0]
        if dataset_directories
        else None
    )


# ============================================================
# FINANCIAL KPI DATA
# ============================================================

@st.cache_data
def load_kpi_summary() -> dict[str, str]:
    """
    Load the KPI summary generated by the Gold layer.
    """

    dataset_path = (
        _find_dataset_dir()
    )

    if dataset_path is None:

        raise FileNotFoundError(
            "The Treasoria dataset directory "
            "was not found inside data/."
        )

    kpi_file_path = (
        dataset_path
        / "gold"
        / "gold_kpi_summary.csv"
    )

    if not kpi_file_path.exists():

        raise FileNotFoundError(
            f"KPI file not found: "
            f"{kpi_file_path}"
        )

    kpi_dataframe = pd.read_csv(
        kpi_file_path
    )

    if not {
        "kpi",
        "value",
    }.issubset(
        kpi_dataframe.columns
    ):

        raise ValueError(
            "The KPI file must contain "
            "the columns 'kpi' and 'value'."
        )

    kpi_dataframe = (
        kpi_dataframe
        .dropna(
            subset=[
                "kpi",
                "value",
            ]
        )
    )

    return {
        str(row["kpi"]).strip():
            str(row["value"]).strip()
        for _, row
        in kpi_dataframe.iterrows()
    }


# ============================================================
# OVERVIEW ANALYTICAL DATA
# ============================================================

@st.cache_data
def load_overview_data() -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
]:
    """
    Load Gold cash-flow and cash-position data plus
    receivables for the Overview visual section.
    """

    dataset_path = (
        _find_dataset_dir()
    )

    if dataset_path is None:

        raise FileNotFoundError(
            "Treassoria dataset not found."
        )

    gold_path = (
        dataset_path
        / "gold"
    )

    monthly = pd.read_csv(
        gold_path
        / "gold_monthly_cash_flow.csv"
    )

    daily = pd.read_csv(
        gold_path
        / "gold_daily_cash_position.csv"
    )

    receivables = pd.read_csv(
        gold_path
        / "gold_receivables_aging.csv"
    )

    monthly["month"] = pd.to_datetime(
        monthly["month"]
    )

    daily["date"] = pd.to_datetime(
        daily["date"]
    )

    return (
        monthly,
        daily,
        receivables,
    )


# ============================================================
# DATA QUALITY
# ============================================================

@st.cache_data
def load_data_quality_status() -> dict:
    """
    Run compact integrity checks against
    the curated Treasoria dataset.
    """

    issues: list[str] = []

    dataset_path = (
        _find_dataset_dir()
    )

    if dataset_path is None:

        return {
            "available": False,
            "issues": [],
            "last_synced": None,
        }

    gold_path = (
        dataset_path
        / "gold"
    )

    silver_path = (
        dataset_path
        / "silver"
    )

    last_synced = None

    kpi_file = (
        gold_path
        / "gold_kpi_summary.csv"
    )

    if kpi_file.exists():

        last_synced = (
            datetime.fromtimestamp(
                kpi_file.stat().st_mtime,
                tz=ZoneInfo(
                    "Europe/Berlin"
                ),
            )
        )

    # --------------------------------------------------------
    # CHECK 1 — ACCOUNTING RECONCILIATION
    # --------------------------------------------------------

    try:

        kpi_df = pd.read_csv(
            kpi_file
        )

        kpi_map = dict(
            zip(
                kpi_df["kpi"],
                kpi_df["value"],
            )
        )

        opening_raw = kpi_map.get(
            "Opening Cash Balance (two accounts)",
            "",
        )

        opening = (
            float(
                opening_raw
                .replace(
                    "EUR",
                    "",
                )
                .replace(
                    ",",
                    "",
                )
                .strip()
            )
            if opening_raw
            else None
        )

        monthly = pd.read_csv(
            gold_path
            / "gold_monthly_cash_flow.csv"
        )

        daily = pd.read_csv(
            gold_path
            / "gold_daily_cash_position.csv"
        )

        net_total = (
            monthly[
                "net_cash_flow"
            ].sum()
        )

        ending = (
            daily.iloc[-1][
                "consolidated_cash_balance"
            ]
        )

        if (
            opening is not None
            and abs(
                (
                    opening
                    + net_total
                )
                - ending
            )
            > 1.0
        ):

            issues.append(
                "Accounting reconciliation mismatch "
                "(opening cash + net flow ≠ "
                "closing balance)"
            )

    except Exception:

        issues.append(
            "Could not verify accounting "
            "reconciliation"
        )


    # --------------------------------------------------------
    # CHECK 2 — SUPPLIER INVOICE TRACEABILITY
    # --------------------------------------------------------

    try:

        supplier = pd.read_csv(
            silver_path
            / "fact_supplier_invoice.csv"
        )

        orphan_count = int(
            supplier[
                "source_transaction_id"
            ]
            .isna()
            .sum()
        )

        if orphan_count > 0:

            issues.append(
                f"{orphan_count} supplier invoice(s) "
                "with no linked bank transaction"
            )

    except Exception:
        pass


    # --------------------------------------------------------
    # CHECK 3 — DUPLICATE TRANSACTION IDS
    # --------------------------------------------------------

    try:

        main = pd.read_csv(
            silver_path
            / "fact_checking_main.csv"
        )

        duplicate_count = int(
            main[
                "transaction_id"
            ]
            .duplicated()
            .sum()
        )

        if duplicate_count > 0:

            issues.append(
                f"{duplicate_count} duplicate "
                "transaction ID(s) detected"
            )

    except Exception:
        pass


    return {
        "available": True,
        "issues": issues,
        "last_synced": last_synced,
    }


def render_data_quality_badge() -> None:
    """
    Display a compact trust signal.
    """

    status = (
        load_data_quality_status()
    )

    if not status[
        "available"
    ]:

        st.caption(
            "○ Data quality check unavailable — "
            "dataset not found"
        )

        return


    if status[
        "issues"
    ]:

        label = (
            "🟠 Data quality issue detected · "
            f"{len(status['issues'])} "
            "item(s) need review"
        )

        with st.popover(
            label
        ):

            st.markdown(
                "**Issues found:**"
            )

            for issue in status[
                "issues"
            ]:

                st.markdown(
                    f"- {issue}"
                )

    else:

        synced = (
            status[
                "last_synced"
            ].strftime(
                "%Y-%m-%d %H:%M"
            )
            if status[
                "last_synced"
            ]
            else "unknown"
        )

        with st.popover(
            f"🟢 Data verified · "
            f"last synced {synced}"
        ):

            st.markdown(
                "**All integrity checks passed**"
            )

            st.markdown(
                "✓ Opening cash + net cash flow "
                "= closing balance"
            )

            st.markdown(
                "✓ Supplier invoices linked "
                "to source transactions"
            )

            st.markdown(
                "✓ No duplicate transaction IDs"
            )


# ============================================================
# NAVIGATION
# ============================================================

PAGES = [
    "Overview",
    "Transactions",
    "Invoices & OCR",
    "Cash-Flow Forecast",
    "Liquidity Risk",
    "What-if Simulator",
    "AI Financial Assistant",
]


# ============================================================
# CUSTOM CSS
# ============================================================

st.markdown(
    """
    <link rel="preconnect"
          href="https://fonts.googleapis.com">

    <link href="
        https://fonts.googleapis.com/css2?
        family=Fraunces:opsz,wght@9..144,400;
        9..144,500;9..144,600;9..144,700&
        family=Inter:wght@400;500;600;700&
        family=IBM+Plex+Mono:wght@400;500;600&
        display=swap"
        rel="stylesheet">

    <style>

        :root {

            --ink: #0A1B33;
            --ink-soft: #3E4C63;

            --ivory: #FAF7F0;
            --card: #FFFFFF;

            --line: #E8E1D3;

            --gold: #C9A24B;
            --gold-soft: #E4CD94;
            --gold-bg: #F6EEDB;

            --sage: #3F7A5C;
            --sage-bg: #E7F1EA;

            --amber: #B8763A;
            --amber-bg: #F6E9D9;

            --slate: #5B6472;
        }


        /* ==================================================
           FULL SCREEN LAYOUT
           ================================================== */

        .stApp {

            background:
                radial-gradient(
                    circle at top right,
                    rgba(201,162,75,0.08),
                    transparent 30%
                ),
                var(--ivory);

            color: var(--ink);
        }


        [data-testid="stAppViewContainer"]
        .block-container {

            max-width: none !important;

            width: 100% !important;

            padding-left: 3.2rem !important;

            padding-right: 3.2rem !important;

            padding-top: 2.2rem !important;

            padding-bottom: 4rem !important;
        }


        [data-testid="stSidebar"] {

            min-width: 320px !important;

            max-width: 320px !important;

            width: 320px !important;

            background:

                radial-gradient(
                    circle at 15% 0%,
                    rgba(201,162,75,0.11),
                    transparent 42%
                ),

                linear-gradient(
                    185deg,
                    #0A1B33 0%,
                    #0D2340 55%,
                    #0A1B33 100%
                );

            border-right:
                1px solid
                rgba(201,162,75,0.35);
        }


        [data-testid="stSidebar"]
        > div:first-child {

            width: 320px !important;
        }


        /* ==================================================
           GLOBAL TYPOGRAPHY
           ================================================== */

        html,
        body,
        [class*="css"],
        .stApp {

            font-family:
                'Inter',
                sans-serif;
        }


        div[data-testid="stAppViewContainer"] p,
        div[data-testid="stAppViewContainer"] li,
        div[data-testid="stMarkdownContainer"] p,
        div[data-testid="stMarkdownContainer"] li {

            font-size: 18px !important;

            line-height: 1.65 !important;
        }


        h1,
        h2,
        h3,
        h4 {

            font-family:
                'Fraunces',
                Georgia,
                serif !important;

            color:
                var(--ink);
        }


        div[data-testid="stAppViewContainer"] h1,
        div[data-testid="stAppViewContainer"] h1 * {

            font-size:
                52px !important;

            line-height:
                1.1 !important;

            font-weight:
                600 !important;

            letter-spacing:
                -0.025em !important;
        }


        div[data-testid="stAppViewContainer"] h2,
        div[data-testid="stAppViewContainer"] h2 * {

            font-size:
                34px !important;
        }


        div[data-testid="stAppViewContainer"] h3,
        div[data-testid="stAppViewContainer"] h3 * {

            font-size:
                27px !important;
        }


        [data-testid="stCaptionContainer"],
        [data-testid="stCaptionContainer"] * {

            font-size:
                16px !important;

            line-height:
                1.5 !important;
        }


        /* ==================================================
           HERO
           ================================================== */

        .treasoria-subtitle {

            color:
                var(--slate);

            font-size:
                20px !important;

            line-height:
                1.6 !important;

            margin-top:
                0.35rem;

            margin-bottom:
                1.7rem;
        }


        .subtitle-hero {

            display:
                inline-block;

            font-family:
                'Fraunces',
                Georgia,
                serif !important;

            font-style:
                italic;

            font-weight:
                600;

            font-size:
                31px !important;

            color:
                var(--ink) !important;

            margin-bottom:
                0.3rem;
        }


        .gold-line {

            width:
                100%;

            height:
                2px;

            margin:
                0.6rem 0 1.9rem 0;

            background:

                linear-gradient(
                    90deg,
                    var(--gold) 0%,
                    var(--gold-soft) 42%,
                    rgba(
                        228,
                        205,
                        148,
                        0
                    )
                    100%
                );
        }


        /* ==================================================
           SIDEBAR
           ================================================== */

        [data-testid="stSidebar"] * {

            color:
                #FFFFFF;
        }


        [data-testid="stSidebar"] img {

            display:
                block;

            max-height:
                210px;

            margin:
                0 auto;

            object-fit:
                contain;

            filter:

                drop-shadow(
                    0 5px 16px
                    rgba(
                        201,
                        162,
                        75,
                        0.28
                    )
                );
        }


        [data-testid="stSidebar"] hr {

            border-color:
                rgba(
                    201,
                    162,
                    75,
                    0.28
                );
        }


        [data-testid="stSidebar"]
        div[role="radiogroup"]
        label {

            padding:
                0.86rem
                0.95rem;

            margin-bottom:
                0.28rem;

            border-radius:
                10px;
        }


        [data-testid="stSidebar"]
        div[role="radiogroup"]
        label,

        [data-testid="stSidebar"]
        div[role="radiogroup"]
        label * {

            font-size:
                16px !important;

            font-weight:
                600 !important;
        }


        [data-testid="stSidebar"]
        div[role="radiogroup"]
        label:hover {

            background-color:

                rgba(
                    201,
                    162,
                    75,
                    0.12
                );
        }


        [data-testid="stSidebar"]
        div[role="radiogroup"]
        label:has(
            input:checked
        ) {

            border-left:
                3px solid
                var(--gold);

            background:

                linear-gradient(
                    90deg,
                    rgba(
                        201,
                        162,
                        75,
                        0.19
                    ),
                    rgba(
                        201,
                        162,
                        75,
                        0.02
                    )
                );
        }


        [data-testid="stSidebar"]
        input[type="radio"] {

            display:
                none;
        }


        /* ==================================================
           COMPANY CARD
           ================================================== */

        .company-card {

            padding:
                1.15rem
                1.05rem
                1rem;

            margin-bottom:
                0.3rem;

            border:

                1px solid
                rgba(
                    201,
                    162,
                    75,
                    0.33
                );

            border-radius:
                13px;

            background:

                rgba(
                    255,
                    255,
                    255,
                    0.05
                );

            position:
                relative;

            overflow:
                hidden;
        }


        .company-card::before {

            content:
                "";

            position:
                absolute;

            top:
                0;

            left:
                0;

            right:
                0;

            height:
                3px;

            background:

                linear-gradient(
                    90deg,
                    var(--gold),
                    var(--gold-soft),
                    var(--gold)
                );
        }


        .company-card-name {

            font-family:
                'Fraunces',
                serif !important;

            font-size:
                20px !important;

            font-weight:
                600;

            color:
                #FFFFFF !important;

            margin-bottom:
                0.42rem;
        }


        .company-card-owner {

            font-size:
                14px !important;

            font-style:
                italic;

            color:
                #C7CEDE !important;

            margin-bottom:
                0.45rem;
        }


        .company-card-address,
        .company-card-sector {

            font-size:
                14px !important;

            color:
                #A9B6CC !important;

            line-height:
                1.55 !important;
        }


        .company-card-sector {

            margin-top:
                0.35rem;
        }


        .company-card-updated {

            display:
                block;

            font-size:
                12px !important;

            color:
                #7C8BA8 !important;

            margin-top:
                0.55rem;

            font-family:
                'IBM Plex Mono',
                monospace;
        }


        /* ==================================================
           SIDEBAR FORM
           ================================================== */

        [data-testid="stSidebar"]
        [data-testid="stExpander"],

        [data-testid="stSidebar"]
        [data-testid="stExpander"] details,

        [data-testid="stSidebar"]
        [data-testid="stExpander"] summary,

        [data-testid="stSidebar"]
        [data-testid="stExpanderDetails"],

        [data-testid="stSidebar"]
        [data-testid="stForm"],

        [data-testid="stSidebar"]
        [data-testid="stVerticalBlockBorderWrapper"] {

            background-color:
                transparent !important;

            border-color:

                rgba(
                    201,
                    162,
                    75,
                    0.28
                )
                !important;

            color:
                #E9ECF2 !important;
        }


        [data-testid="stSidebar"]
        [data-testid="stExpander"] {

            border:

                1px solid
                rgba(
                    201,
                    162,
                    75,
                    0.28
                )
                !important;

            border-radius:
                10px !important;
        }


        [data-testid="stSidebar"]
        [data-testid="stExpander"]
        summary,

        [data-testid="stSidebar"]
        [data-testid="stExpander"]
        summary * {

            font-size:
                15px !important;
        }


        /* ==================================================
           KPI CARDS
           ================================================== */

        div[data-testid="stMetric"] {

            min-height:
                150px;

            padding:
                1.55rem
                1.7rem !important;

            border:
                1px solid
                var(--line);

            border-radius:
                15px;

            background-color:
                var(--card);

            box-shadow:

                0 10px 30px
                rgba(
                    10,
                    27,
                    51,
                    0.06
                );

            position:
                relative;

            overflow:
                hidden;
        }


        div[data-testid="stMetric"]::before {

            content:
                "";

            position:
                absolute;

            top:
                0;

            left:
                0;

            width:
                4px;

            height:
                100%;

            background:

                linear-gradient(
                    180deg,
                    var(--gold),
                    rgba(
                        201,
                        162,
                        75,
                        0
                    )
                );
        }


        div[data-testid="stMetricValue"],
        div[data-testid="stMetricValue"] * {

            font-family:
                'Fraunces',
                serif !important;

            font-weight:
                600 !important;

            color:
                var(--ink) !important;

            font-size:
                34px !important;

            line-height:
                1.22 !important;

            white-space:
                normal !important;

            overflow:
                visible !important;

            text-overflow:
                unset !important;
        }


        div[data-testid="stMetricLabel"],
        div[data-testid="stMetricLabel"] * {

            color:
                var(--slate) !important;

            font-size:
                16px !important;

            font-weight:
                600 !important;
        }


        /* ==================================================
           SECTION TITLES
           ================================================== */

        .section-title {

            font-family:
                'Fraunces',
                serif !important;

            font-size:
                34px !important;

            font-weight:
                600 !important;

            color:
                var(--ink) !important;

            margin-top:
                2.4rem;

            margin-bottom:
                1.25rem;
        }


        /* ==================================================
           OVERVIEW INSIGHT CARDS
           ================================================== */

        .insight-card {

            border:
                1px solid
                var(--line);

            border-radius:
                14px;

            background:
                var(--card);

            padding:
                1.25rem
                1.4rem;

            margin-bottom:
                0.85rem;

            box-shadow:

                0 8px 24px
                rgba(
                    10,
                    27,
                    51,
                    0.05
                );
        }


        .insight-label {

            font-size:
                14px !important;

            font-weight:
                600;

            color:
                var(--slate) !important;

            text-transform:
                uppercase;

            letter-spacing:
                0.05em;
        }


        .insight-value {

            font-family:
                'Fraunces',
                serif !important;

            font-size:
                27px !important;

            font-weight:
                600;

            color:
                var(--ink) !important;

            margin-top:
                0.25rem;
        }


        .insight-note {

            font-size:
                14px !important;

            color:
                var(--slate) !important;

            margin-top:
                0.2rem;
        }


        /* ==================================================
           MODULE CARDS
           ================================================== */

        .module-card {

            min-height:
                235px;

            padding:
                1.9rem;

            border:
                1px solid
                var(--line);

            border-top:
                3px solid
                var(--gold);

            border-radius:
                15px;

            background:

                linear-gradient(
                    160deg,
                    #FFFFFF 0%,
                    #FCFAF4 100%
                );

            box-shadow:

                0 10px 28px
                rgba(
                    10,
                    27,
                    51,
                    0.06
                );
        }


        .module-card h4 {

            margin:
                0
                0
                0.9rem
                0;

            font-size:
                25px !important;

            color:
                var(--ink) !important;
        }


        .module-card p {

            color:
                var(--slate) !important;

            font-size:
                17px !important;

            line-height:
                1.6 !important;
        }


        .status-ready {

            color:
                #1D5FA8 !important;

            font-weight:
                700;

            font-size:
                16px !important;
        }


        .status-planned {

            color:
                var(--amber) !important;

            font-weight:
                700;

            font-size:
                16px !important;
        }


        /* ==================================================
           WORKFLOW
           ================================================== */

        .workflow-card {

            border:
                1px solid
                var(--line);

            border-radius:
                15px;

            background:
                var(--card);

            box-shadow:

                0 10px 28px
                rgba(
                    10,
                    27,
                    51,
                    0.05
                );

            padding:
                0.4rem
                1.9rem;

            margin-bottom:
                1rem;
        }


        .workflow-row {

            display:
                flex;

            align-items:
                center;

            gap:
                1.2rem;

            padding:
                1.18rem
                0;

            border-bottom:

                1px solid
                #F1ECDE;
        }


        .workflow-row:last-child {

            border-bottom:
                none;
        }


        .workflow-num {

            font-family:
                'IBM Plex Mono',
                monospace !important;

            font-size:
                16px !important;

            font-weight:
                600;

            color:
                var(--gold);

            background:
                var(--gold-bg);

            width:
                2.7rem;

            height:
                2.7rem;

            border-radius:
                50%;

            display:
                flex;

            align-items:
                center;

            justify-content:
                center;

            flex-shrink:
                0;
        }


        .workflow-text {

            font-size:
                18px !important;

            color:
                var(--ink-soft) !important;
        }


        /* ==================================================
           CHAT
           ================================================== */

        .assistant-intro {

            padding:
                1.2rem
                1.4rem;

            margin-bottom:
                1.1rem;

            border-left:
                4px solid
                var(--gold);

            border-radius:
                0
                12px
                12px
                0;

            background:

                linear-gradient(
                    90deg,
                    rgba(
                        201,
                        162,
                        75,
                        0.11
                    ),
                    rgba(
                        10,
                        27,
                        51,
                        0.03
                    )
                );

            color:
                var(--ink);

            font-size:
                17px !important;
        }


        [data-testid="stChatMessage"] {

            margin-bottom:
                0.9rem;

            border:
                1px solid
                var(--line);

            border-radius:
                14px;

            background-color:
                var(--card);

            box-shadow:

                0 5px 16px
                rgba(
                    10,
                    27,
                    51,
                    0.05
                );
        }


        /* ==================================================
           BUTTONS
           ================================================== */

        .stButton > button {

            border:
                1px solid
                var(--gold);

            border-radius:
                9px;

            background:

                linear-gradient(
                    135deg,
                    #0A1B33,
                    #16345E
                );

            color:
                #FFFFFF;

            font-weight:
                650;
        }


        .stButton > button:hover {

            border-color:
                var(--gold-soft);

            color:
                #FFFFFF;

            box-shadow:

                0 6px 18px
                rgba(
                    201,
                    162,
                    75,
                    0.28
                );
        }


        /* ==================================================
           DATA QUALITY POPOVER
           ================================================== */

        [data-testid="stPopover"]
        > button,

        [data-testid="stPopover"]
        > button * {

            border-radius:
                30px !important;

            font-weight:
                600 !important;

            font-size:
                15px !important;

            box-shadow:
                none !important;

            padding-top:
                0.55rem !important;

            padding-bottom:
                0.55rem !important;
        }


        div[data-testid="stPopoverBody"] {

            background-color:
                #FFFFFF !important;

            border:
                1px solid
                var(--line) !important;

            border-radius:
                12px !important;

            box-shadow:

                0 16px 40px
                rgba(
                    10,
                    27,
                    51,
                    0.18
                )
                !important;

            min-width:
                360px !important;
        }


        div[data-testid="stPopoverBody"] * {

            color:
                var(--ink) !important;

            font-size:
                15px !important;

            line-height:
                1.6 !important;
        }


        /* ==================================================
           FOOTER
           ================================================== */

        .footer-text {

            margin-top:
                3rem;

            color:
                #B7AE97;

            text-align:
                center;

            font-size:
                12px !important;

            letter-spacing:
                0.16em;

            font-family:
                'IBM Plex Mono',
                monospace;
        }


        /* ==================================================
           RESPONSIVE
           ================================================== */

        @media (
            max-width:
            1100px
        ) {

            [data-testid="stAppViewContainer"]
            .block-container {

                padding-left:
                    1.5rem !important;

                padding-right:
                    1.5rem !important;
            }

        }

    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SHARED HELPERS
# ============================================================

def render_placeholder_page(
    icon: str,
    title: str,
    description: str,
    bullet_points: list[str] | None = None,
) -> None:
    """
    Render a consistent placeholder.
    """

    st.title(
        f"{icon} {title}"
    )

    st.markdown(
        '<div class="gold-line"></div>',
        unsafe_allow_html=True,
    )

    st.info(
        description
    )

    if bullet_points:

        st.markdown(
            "Planned indicators / fields:\n\n"
            + "\n".join(
                f"- {point}"
                for point
                in bullet_points
            )
        )


def render_feedback(
    message_index: int,
) -> None:
    """
    Render assistant feedback controls.
    """

    key = (
        f"feedback_{message_index}"
    )

    current_vote = (
        st.session_state.get(
            key
        )
    )

    col_up, col_down, _ = (
        st.columns(
            [
                1,
                1,
                10,
            ]
        )
    )

    with col_up:

        if st.button(
            "👍",
            key=f"{key}_up",
            type=(
                "primary"
                if current_vote
                == "up"
                else "secondary"
            ),
        ):

            st.session_state[key] = (
                None
                if current_vote
                == "up"
                else "up"
            )

            st.rerun()


    with col_down:

        if st.button(
            "👎",
            key=f"{key}_down",
            type=(
                "primary"
                if current_vote
                == "down"
                else "secondary"
            ),
        ):

            st.session_state[key] = (
                None
                if current_vote
                == "down"
                else "down"
            )

            st.rerun()


# ============================================================
# MODEL LOADING
# ============================================================

@st.cache_resource(
    show_spinner=False
)
def load_models():

    llm = (
        initialise_llm()
    )

    embed_model = (
        get_embedding_model()
    )

    return (
        llm,
        embed_model,
    )


def initialise_chat_engine():

    llm, embed_model = (
        load_models()
    )

    return get_chat_engine(
        llm=llm,
        embed_model=embed_model,
    )


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.image(
        "assets/treasoria_logo.png",
        width="stretch",
    )

    st.markdown(
        """
        <p style="
            margin-top:-1rem;
            text-align:center;
            color:#E4CD94;
            font-size:12px;
            letter-spacing:0.14em;
            font-weight:600;
        ">
            PREDICT. EXPLAIN. SIMULATE. DECIDE.
        </p>
        """,
        unsafe_allow_html=True,
    )

    st.divider()


    st.markdown(
        f"""
        <div class="company-card">

            <div class="company-card-name">
                {ACTIVE_COMPANY['name']}
            </div>

            <div class="company-card-owner">
                Owner:
                {ACTIVE_COMPANY['owner']}
            </div>

            <div class="company-card-address">
                {ACTIVE_COMPANY['address']}
                <br>
                {ACTIVE_COMPANY['city']}
            </div>

            <div class="company-card-sector">
                {ACTIVE_COMPANY['sector']}
            </div>

            <div class="company-card-updated">
                Last online:
                {ACTIVE_COMPANY['last_updated']}
            </div>

        </div>
        """,
        unsafe_allow_html=True,
    )


    st.divider()


    selected_page = st.radio(
        "Navigation",
        options=PAGES,
        label_visibility="collapsed",
    )


    st.divider()


    with st.expander(
        "✏️ Edit company profile",
        expanded=False,
    ):

        with st.form(
            "company_profile_form"
        ):

            new_name = (
                st.text_input(
                    "Café name",
                    value=ACTIVE_COMPANY[
                        "name"
                    ],
                    placeholder=(
                        "e.g. Code & Coffee GmbH"
                    ),
                )
            )

            new_address = (
                st.text_input(
                    "Address",
                    value=ACTIVE_COMPANY[
                        "address"
                    ],
                )
            )

            new_city = (
                st.text_input(
                    "City / Country",
                    value=ACTIVE_COMPANY[
                        "city"
                    ],
                )
            )

            new_owner = (
                st.text_input(
                    "Owner name",
                    value=ACTIVE_COMPANY[
                        "owner"
                    ],
                )
            )

            new_sector = (
                st.text_input(
                    "Sector",
                    value=ACTIVE_COMPANY[
                        "sector"
                    ],
                )
            )


            submitted = (
                st.form_submit_button(
                    "Save",
                    width="stretch",
                )
            )


            if submitted:

                st.session_state.company_profile.update(
                    {
                        "name":
                            new_name,

                        "owner":
                            new_owner,

                        "address":
                            new_address,

                        "city":
                            new_city,

                        "sector":
                            new_sector,
                    }
                )

                save_company(
                    st.session_state.company_profile
                )

                st.success(
                    "Company profile updated."
                )

                st.rerun()


# ============================================================
# OVERVIEW
# ============================================================

if selected_page == "Overview":

    st.title(
        "Treasoria Overview"
    )


    st.markdown(
        f"""
        <div class="treasoria-subtitle">

            <span class="subtitle-hero">
                See Tomorrow's Cash.
                Make Better Decisions Today.
            </span>

            <br>

            Financial intelligence for
            {ACTIVE_COMPANY["name"]}

        </div>
        """,
        unsafe_allow_html=True,
    )


    st.markdown(
        '<div class="gold-line"></div>',
        unsafe_allow_html=True,
    )


    render_data_quality_badge()


    st.write("")


    # ========================================================
    # KPI SECTION
    # ========================================================

    try:

        kpi_summary = (
            load_kpi_summary()
        )


        def get_kpi(
            kpi_name: str,
        ) -> str:

            return (
                kpi_summary.get(
                    kpi_name,
                    "Not available",
                )
            )


        runway_raw = (
            get_kpi(
                "Runway"
            )
        )


        if (
            "Not burning cash"
            in runway_raw
        ):

            runway_display = (
                "No current cash burn"
            )

            runway_note = (
                "Positive 3-month "
                "average net flow"
            )

        else:

            runway_display = (
                runway_raw
            )

            runway_note = (
                "Based on recent "
                "cash-flow profile"
            )


        kpi_column_1, (
            kpi_column_2
        ), kpi_column_3 = (
            st.columns(3)
        )


        with kpi_column_1:

            st.metric(
                label=(
                    "Closing cash balance"
                ),
                value=get_kpi(
                    "Consolidated Cash Balance "
                    "(end of period)"
                ),
            )


        with kpi_column_2:

            st.metric(
                label=(
                    "Average monthly "
                    "net cash flow"
                ),
                value=get_kpi(
                    "Average Monthly "
                    "Net Cash Flow"
                ),
            )


        with kpi_column_3:

            st.metric(
                label=(
                    "Cash-collected revenue"
                ),
                value=get_kpi(
                    "Cash-Collected Revenue "
                    "(24 months)"
                ),
            )


        st.write("")


        kpi_column_4, (
            kpi_column_5
        ), kpi_column_6 = (
            st.columns(3)
        )


        with kpi_column_4:

            st.metric(
                label=(
                    "Open customer "
                    "receivables"
                ),
                value=get_kpi(
                    "Open Receivables"
                ),
            )


        with kpi_column_5:

            st.metric(
                label=(
                    "Closing credit-card debt"
                ),
                value=get_kpi(
                    "Credit Card Debt "
                    "(end of period)"
                ),
            )


        with kpi_column_6:

            st.metric(
                label="Cash runway",
                value=runway_display,
            )

            st.caption(
                runway_note
            )


        st.caption(
            "Financial results calculated "
            "from the validated Treasoria "
            "Gold data pipeline."
        )


    except (
        FileNotFoundError,
        ValueError,
        pd.errors.ParserError,
    ) as error:

        st.error(
            "The financial KPI summary "
            "could not be loaded."
        )

        st.code(
            str(error),
            language="text",
        )


    # ========================================================
    # CASH INTELLIGENCE VISUAL
    # ========================================================

    st.markdown(
        """
        <h2 class="section-title">
            Cash Position & Monthly Net Cash Flow
        </h2>
        """,
        unsafe_allow_html=True,
    )


    try:

        monthly, daily, receivables = (
            load_overview_data()
        )


        chart_column, (
            signal_column
        ) = st.columns(
            [
                2.25,
                1,
            ],
            gap="large",
        )


        with chart_column:

            st.markdown(
                "### Consolidated Cash Position"
            )


            latest_date = (
                daily["date"].max()
            )


            one_year_before = (
                latest_date
                - pd.DateOffset(
                    months=12
                )
            )


            daily_last_year = (
                daily.loc[
                    daily["date"]
                    >= one_year_before,
                    [
                        "date",
                        "consolidated_cash_balance",
                    ],
                ]
                .copy()
            )


            daily_last_year = (
                daily_last_year
                .set_index(
                    "date"
                )
            )


            st.line_chart(
                daily_last_year,
                height=340,
            )


            st.markdown(
                "### Monthly Net Cash Flow"
            )


            monthly_last_year = (
                monthly
                .sort_values(
                    "month"
                )
                .tail(12)
                [
                    [
                        "month",
                        "net_cash_flow",
                    ]
                ]
                .copy()
            )


            monthly_last_year[
                "month"
            ] = (
                monthly_last_year[
                    "month"
                ]
                .dt.strftime(
                    "%b %Y"
                )
            )


            monthly_last_year = (
                monthly_last_year
                .set_index(
                    "month"
                )
            )


            st.bar_chart(
                monthly_last_year,
                height=300,
            )


        with signal_column:

            st.markdown(
                "### Latest Financial Signals"
            )


            recent_three_month_avg = float(
                monthly
                .sort_values(
                    "month"
                )
                .tail(3)[
                    "net_cash_flow"
                ]
                .mean()
            )


            negative_months = int(
                (
                    monthly[
                        "net_cash_flow"
                    ]
                    < 0
                )
                .sum()
            )


            overdue_count = int(
                (
                    receivables[
                        "status"
                    ]
                    == "open_overdue"
                )
                .sum()
            )


            lowest_row = (
                monthly
                .sort_values(
                    "net_cash_flow"
                )
                .iloc[0]
            )


            lowest_month = (
                pd.to_datetime(
                    lowest_row[
                        "month"
                    ]
                )
                .strftime(
                    "%b %Y"
                )
            )


            lowest_value = float(
                lowest_row[
                    "net_cash_flow"
                ]
            )


            cash_signal = (
                "Positive"
                if recent_three_month_avg
                >= 0
                else "Negative"
            )


            st.markdown(
                f"""
                <div class="insight-card">

                    <div class="insight-label">
                        3-Month Cash Trend
                    </div>

                    <div class="insight-value">
                        {cash_signal}
                    </div>

                    <div class="insight-note">
                        Avg.
                        EUR
                        {recent_three_month_avg:,.2f}
                        / month
                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )


            st.markdown(
                f"""
                <div class="insight-card">

                    <div class="insight-label">
                        Overdue Customer Invoices
                    </div>

                    <div class="insight-value">
                        {overdue_count}
                    </div>

                    <div class="insight-note">
                        Requires collection follow-up
                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )


            st.markdown(
                f"""
                <div class="insight-card">

                    <div class="insight-label">
                        Negative Cash-Flow Months
                    </div>

                    <div class="insight-value">
                        {negative_months} / {len(monthly)}
                    </div>

                    <div class="insight-note">
                        Across the full represented period
                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )


            st.markdown(
                f"""
                <div class="insight-card">

                    <div class="insight-label">
                        Lowest Cash-Flow Month
                    </div>

                    <div class="insight-value">
                        {lowest_month}
                    </div>

                    <div class="insight-note">
                        EUR {lowest_value:,.2f}
                    </div>

                </div>
                """,
                unsafe_allow_html=True,
            )


            st.caption(
                "These are descriptive financial signals "
                "from validated historical data. "
                "The forecast-based Liquidity Risk engine "
                "will add forward-looking risk severity."
            )


    except Exception as error:

        st.info(
            "Cash intelligence charts "
            "could not be loaded."
        )

        st.caption(
            str(error)
        )


    # ========================================================
    # MODULES
    # ========================================================

    st.markdown(
        """
        <h2 class="section-title">
            Treasoria Modules
        </h2>
        """,
        unsafe_allow_html=True,
    )


    column_1, (
        column_2
    ), column_3 = (
        st.columns(
            3,
            gap="large",
        )
    )


    with column_1:

        st.markdown(
            """
            <div class="module-card">

                <h4>
                    📄 Documents & OCR
                </h4>

                <p>
                    Extract, validate and reconcile
                    invoice and financial-document
                    information.
                </p>

                <p class="status-planned">
                    Integration planned
                </p>

            </div>
            """,
            unsafe_allow_html=True,
        )


    with column_2:

        st.markdown(
            """
            <div class="module-card">

                <h4>
                    📈 Forecast & Risk Intelligence
                </h4>

                <p>
                    Forecast future cash positions,
                    quantify uncertainty and detect
                    potential liquidity-risk signals.
                </p>

                <p class="status-ready">
                    Financial data connected
                </p>

            </div>
            """,
            unsafe_allow_html=True,
        )


    with column_3:

        st.markdown(
            """
            <div class="module-card">

                <h4>
                    ✨ AI Financial Assistant
                </h4>

                <p>
                    Exact structured financial answers
                    through SQLite and contextual
                    explanations through RAG.
                </p>

                <p class="status-ready">
                    Ready
                </p>

            </div>
            """,
            unsafe_allow_html=True,
        )


    # ========================================================
    # WORKFLOW
    # ========================================================

    st.markdown(
        """
        <h2 class="section-title">
            Decision-Intelligence Workflow
        </h2>
        """,
        unsafe_allow_html=True,
    )


    workflow_steps = [

        "Extract financial information using OCR.",

        "Validate, clean and transform "
        "the extracted data.",

        "Store trusted financial information.",

        "Calculate financial KPIs.",

        "Forecast future cash positions.",

        "Identify potential liquidity risks.",

        "Simulate alternative business scenarios.",

        "Explain results through the "
        "financial assistant.",
    ]


    workflow_html = "".join(

        (
            '<div class="workflow-row">'
            f'<div class="workflow-num">{i:02d}</div>'
            f'<div class="workflow-text">{step}</div>'
            '</div>'
        )

        for i, step
        in enumerate(
            workflow_steps,
            start=1,
        )
    )


    st.markdown(
        (
            '<div class="workflow-card">'
            f'{workflow_html}'
            '</div>'
        ),
        unsafe_allow_html=True,
    )


# ============================================================
# TRANSACTIONS
# ============================================================

elif selected_page == "Transactions":

    render_placeholder_page(
        icon="📋",
        title="Transactions",
        description=(
            "This page will show the full "
            "filterable transaction ledger once "
            "the Silver layer is connected."
        ),
        bullet_points=[
            "date, amount, category, counterparty and flow type",
            "bank account and transaction source",
            "reconciliation status",
            "internal vs. external flag",
            "category breakdown",
            "CSV export of the active filter",
        ],
    )


# ============================================================
# INVOICES & OCR
# ============================================================

elif selected_page == "Invoices & OCR":

    st.title(
        "📄 Invoices & OCR"
    )

    st.markdown(
        '<div class="gold-line"></div>',
        unsafe_allow_html=True,
    )

    st.info(
        "This module will extract fields "
        "from invoices and financial documents "
        "before sending validated data "
        "to the ETL pipeline."
    )

    st.file_uploader(
        "Upload a financial document",
        type=[
            "pdf",
            "png",
            "jpg",
            "jpeg",
        ],
        disabled=True,
    )

    st.caption(
        "Document upload is disabled until "
        "the OCR pipeline is connected."
    )


# ============================================================
# FORECAST
# ============================================================

elif selected_page == "Cash-Flow Forecast":

    render_placeholder_page(
        icon="📈",
        title="Cash-Flow Forecast",
        description=(
            "Historical cash flow, forecasts, "
            "confidence intervals and model "
            "comparison will appear here once "
            "the forecasting module is connected."
        ),
        bullet_points=[
            "30 / 60 / 90-day forecast",
            "confidence intervals",
            "actual vs forecast comparison",
            "model comparison",
            "MAE / RMSE / MAPE",
        ],
    )


# ============================================================
# LIQUIDITY RISK
# ============================================================

elif selected_page == "Liquidity Risk":

    render_placeholder_page(
        icon="⚠️",
        title="Liquidity Risk",
        description=(
            "Risk periods, overdue invoices "
            "and suggested actions will appear "
            "here once the risk engine "
            "is connected."
        ),
        bullet_points=[
            "projected negative cash",
            "large upcoming payments",
            "overdue client collections",
            "low cash balance alerts",
            "short runway alerts",
            "exceptional outflows",
            "negative cash-flow trend",
            "high forecast uncertainty",
            "customer concentration risk",
        ],
    )


# ============================================================
# WHAT-IF SIMULATOR
# ============================================================

elif selected_page == "What-if Simulator":

    render_placeholder_page(
        icon="🧮",
        title="What-if Simulator",
        description=(
            "Users will be able to simulate "
            "delayed payments, expense increases, "
            "new hires and other scenarios once "
            "this module is connected."
        ),
        bullet_points=[
            "reference scenario",
            "modified scenario",
            "projected final balance",
            "minimum projected balance",
            "low-point date",
            "days below critical threshold",
            "save scenarios",
            "compare scenarios",
            "export scenarios",
        ],
    )


# ============================================================
# AI FINANCIAL ASSISTANT
# ============================================================

elif selected_page == (
    "AI Financial Assistant"
):

    if (
        "messages"
        not in st.session_state
    ):

        st.session_state.messages = []


    if (
        "chat_engine"
        not in st.session_state
    ):

        with st.spinner(
            "Initialising the "
            "Treasoria assistant..."
        ):

            st.session_state.chat_engine = (
                initialise_chat_engine()
            )


    title_column, (
        button_column
    ) = st.columns(
        [
            4,
            1,
        ],
        vertical_alignment="center",
    )


    with title_column:

        st.title(
            "✨ AI Financial Assistant"
        )

        st.caption(
            "Precise financial answers "
            "from structured data and "
            "validated Treasoria documentation."
        )


    with button_column:

        if st.button(
            "＋ New Chat",
            width="stretch",
        ):

            st.session_state.messages = []

            with st.spinner(
                "Starting a new conversation..."
            ):

                st.session_state.chat_engine = (
                    initialise_chat_engine()
                )

            st.rerun()


    st.markdown(
        """
        <div class="assistant-intro">

            Ask Treasoria about cash balances,
            cash flow, invoices, receivables,
            payment behaviour, accounting controls
            or financial events.

        </div>
        """,
        unsafe_allow_html=True,
    )


    st.caption(
        "Treassoria combines structured "
        "financial data with validated "
        "documentation to provide precise "
        "financial answers and contextual "
        "explanations."
    )


    for (
        message_index,
        message,
    ) in enumerate(
        st.session_state.messages
    ):

        with st.chat_message(
            message["role"]
        ):

            st.markdown(
                message["content"]
            )

            if (
                message["role"]
                == "assistant"
            ):

                render_feedback(
                    message_index
                )


    user_question = (
        st.chat_input(
            "Ask a financial question "
            "about Treasoria..."
        )
    )


    if user_question:

        st.session_state.messages.append(
            {
                "role":
                    "user",

                "content":
                    user_question,
            }
        )


        with st.chat_message(
            "user"
        ):

            st.markdown(
                user_question
            )


        with st.chat_message(
            "assistant"
        ):

            try:

                response_start = (
                    time.perf_counter()
                )


                with st.spinner(
                    "Analysing your "
                    "financial question..."
                ):

                    # ========================================
                    # HYBRID SQL + RAG
                    # ========================================

                    sql_response = (
                        answer_sql_question(
                            user_question
                        )
                    )


                    if (
                        sql_response
                        is not None
                    ):

                        response = (
                            sql_response
                        )

                        response_text = (
                            str(
                                response
                            )
                        )

                        sources = []


                    else:

                        response = (
                            st.session_state
                            .chat_engine
                            .chat(
                                user_question
                            )
                        )

                        response_text = (
                            str(
                                response
                            )
                        )

                        sources = []


                        for (
                            source_node
                        ) in getattr(
                            response,
                            "source_nodes",
                            [],
                        ):

                            metadata = (
                                source_node
                                .node
                                .metadata
                                or {}
                            )


                            source_name = (

                                metadata.get(
                                    "file_name"
                                )

                                or metadata.get(
                                    "filename"
                                )

                                or metadata.get(
                                    "file_path"
                                )

                                or (
                                    "Treasoria "
                                    "document"
                                )
                            )


                            sources.append(
                                {
                                    "name":
                                        str(
                                            source_name
                                        ),

                                    "text":
                                        source_node
                                        .node
                                        .get_content(),

                                    "score":
                                        source_node
                                        .score,
                                }
                            )


                response_time = (
                    time.perf_counter()
                    - response_start
                )


                st.markdown(
                    response_text
                )


                st.session_state.messages.append(
                    {
                        "role":
                            "assistant",

                        "content":
                            response_text,

                        "response_time":
                            response_time,

                        "sources":
                            sources,
                    }
                )


                render_feedback(
                    len(
                        st.session_state.messages
                    )
                    - 1
                )


            except Exception as error:

                st.error(
                    "Treasoria could not "
                    "generate a response. "
                    "Please try again."
                )

                st.exception(
                    error
                )


# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
    <p class="footer-text">

        TREASORIA ·
        PREDICT ·
        EXPLAIN ·
        SIMULATE ·
        DECIDE

    </p>
    """,
    unsafe_allow_html=True,
)