import json
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import streamlit as st
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from src.engine import get_chat_engine
from src.model_loader import (
    get_embedding_model,
    initialise_llm,
)
from src.sql_engine import (
    answer_sql_question,
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Treasoria",
    page_icon="💎",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# ACTIVE COMPANY
# ============================================================

COMPANY_PROFILE_PATH = Path("data/company_profile.json")

COMPANY_NAME = "Code & Coffee GmbH"
COMPANY_OWNER = "Blue Jesus"
COMPANY_ADDRESS = "Ravensberger Str. 22"
COMPANY_CITY = "33602 Bielefeld, Germany"
COMPANY_SECTOR = "International Café & Gastronomy"
COMPANY_STATUS = "Synthetic business identity"

DEFAULT_COMPANY = {
    "company_id": "code_and_coffee",
    "name": COMPANY_NAME,
    "owner": COMPANY_OWNER,
    "address": COMPANY_ADDRESS,
    "city": COMPANY_CITY,
    "sector": COMPANY_SECTOR,
    "status": COMPANY_STATUS,
    "last_updated": "never",
}


def _now_berlin() -> str:
    """
    Return the current local time for Bielefeld.
    """

    return datetime.now(ZoneInfo("Europe/Berlin")).strftime(
        "%Y-%m-%d %H:%M"
    )


def load_company() -> dict:
    """
    Load the saved company profile.

    DEFAULT_COMPANY is used as a safe fallback when no
    editable profile has been saved yet.
    """

    profile = DEFAULT_COMPANY.copy()

    if COMPANY_PROFILE_PATH.exists():
        with open(COMPANY_PROFILE_PATH, "r", encoding="utf-8") as file:
            saved = json.load(file)

        profile.update(saved)

    return profile


def save_company(profile: dict) -> None:
    """
    Save the active company profile.
    """

    profile["last_updated"] = _now_berlin()

    COMPANY_PROFILE_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(COMPANY_PROFILE_PATH, "w", encoding="utf-8") as file:
        json.dump(profile, file, ensure_ascii=False, indent=2)


if "company_profile" not in st.session_state:
    st.session_state.company_profile = load_company()

ACTIVE_COMPANY = st.session_state.company_profile


# ============================================================
# DATASET LOCATION
# ============================================================

def _find_dataset_dir() -> Path | None:
    """
    Locate the Treasoria structured dataset.
    """

    project_root = Path(__file__).parent
    data_path = project_root / "data"

    dataset_directories = [
        directory
        for directory in data_path.glob("Treasoria_Datasets*")
        if directory.is_dir()
    ]

    return dataset_directories[0] if dataset_directories else None


# ============================================================
# FINANCIAL KPI DATA
# ============================================================

@st.cache_data
def load_kpi_summary() -> dict[str, str]:
    """
    Load the KPI summary generated by the Gold layer.
    """

    dataset_path = _find_dataset_dir()

    if dataset_path is None:
        raise FileNotFoundError(
            "The Treasoria dataset directory "
            "was not found inside data/."
        )

    kpi_file_path = dataset_path / "gold" / "gold_kpi_summary.csv"

    if not kpi_file_path.exists():
        raise FileNotFoundError(
            f"KPI file not found: {kpi_file_path}"
        )

    kpi_dataframe = pd.read_csv(kpi_file_path)

    if not {"kpi", "value"}.issubset(kpi_dataframe.columns):
        raise ValueError(
            "The KPI file must contain the columns "
            "'kpi' and 'value'."
        )

    kpi_dataframe = kpi_dataframe.dropna(subset=["kpi", "value"])

    return {
        str(row["kpi"]).strip(): str(row["value"]).strip()
        for _, row in kpi_dataframe.iterrows()
    }


# ============================================================
# DATA QUALITY
# ============================================================

@st.cache_data
def load_data_quality_status() -> dict:
    """
    Run compact integrity checks against
    the curated Treasoria dataset.
    """

    issues: list[str] = []
    dataset_path = _find_dataset_dir()

    if dataset_path is None:
        return {"available": False, "issues": [], "last_synced": None}

    gold_path = dataset_path / "gold"
    silver_path = dataset_path / "silver"

    last_synced = None
    kpi_file = gold_path / "gold_kpi_summary.csv"

    if kpi_file.exists():
        last_synced = datetime.fromtimestamp(
            kpi_file.stat().st_mtime, tz=ZoneInfo("Europe/Berlin")
        )

    # --------------------------------------------------------
    # CHECK 1: ACCOUNTING RECONCILIATION
    # --------------------------------------------------------

    try:
        kpi_df = pd.read_csv(kpi_file)
        kpi_map = dict(zip(kpi_df["kpi"], kpi_df["value"]))

        opening_raw = kpi_map.get(
            "Opening Cash Balance (two accounts)", ""
        )

        opening = (
            float(opening_raw.replace("EUR", "").replace(",", "").strip())
            if opening_raw else None
        )

        monthly = pd.read_csv(gold_path / "gold_monthly_cash_flow.csv")
        daily = pd.read_csv(gold_path / "gold_daily_cash_position.csv")

        net_total = monthly["net_cash_flow"].sum()
        ending = daily.iloc[-1]["consolidated_cash_balance"]

        if opening is not None and abs((opening + net_total) - ending) > 1.0:
            issues.append(
                "Accounting reconciliation mismatch "
                "(opening cash + net flow ≠ closing balance)"
            )

    except Exception:
        issues.append("Could not verify accounting reconciliation")

    # --------------------------------------------------------
    # CHECK 2: SUPPLIER INVOICE TRACEABILITY
    # --------------------------------------------------------

    try:
        supplier = pd.read_csv(silver_path / "fact_supplier_invoice.csv")
        orphan_count = int(supplier["source_transaction_id"].isna().sum())

        if orphan_count > 0:
            issues.append(
                f"{orphan_count} supplier invoice(s) "
                "with no linked bank transaction"
            )

    except Exception:
        pass

    # --------------------------------------------------------
    # CHECK 3: DUPLICATE MAIN TRANSACTION IDS
    # --------------------------------------------------------

    try:
        main = pd.read_csv(silver_path / "fact_checking_main.csv")
        duplicate_count = int(main["transaction_id"].duplicated().sum())

        if duplicate_count > 0:
            issues.append(
                f"{duplicate_count} duplicate transaction ID(s) detected"
            )

    except Exception:
        pass

    return {"available": True, "issues": issues, "last_synced": last_synced}


def render_data_quality_badge() -> None:
    """
    Display a compact trust signal on the Overview page.
    """

    status = load_data_quality_status()

    if not status["available"]:
        st.caption("○ Data quality check unavailable — dataset not found")
        return

    if status["issues"]:
        label = (
            "🟠 Data quality issue detected · "
            f"{len(status['issues'])} item(s) need review"
        )

        with st.popover(label):
            st.markdown("**Issues found:**")
            for issue in status["issues"]:
                st.markdown(f"- {issue}")

    else:
        synced = (
            status["last_synced"].strftime("%Y-%m-%d %H:%M")
            if status["last_synced"] else "unknown"
        )

        with st.popover(f"🟢 Data verified · last synced {synced}"):
            st.markdown("All integrity checks passed:")
            st.markdown("- Opening cash + net cash flow = closing balance ✓")
            st.markdown("- All supplier invoices linked to a source transaction ✓")
            st.markdown("- No duplicate transaction IDs ✓")


# ============================================================
# OVERVIEW CHART + RISK SIGNAL
# ============================================================
# Both read straight from the Gold layer that's already validated
# for the KPI cards above — this is real history, not a mockup.
# The risk badge is a genuinely computed (if intentionally light)
# signal: it looks at whether any of the last 3 months went cash-
# flow negative, the same underlying fact the dynamic Runway KPI
# already uses. It is NOT the full 6-rule Liquidity Risk engine —
# that's still its own page — so the caption says so explicitly
# rather than implying more coverage than exists yet.

@st.cache_data
def load_cash_position_chart_data():
    dataset_path = _find_dataset_dir()

    if dataset_path is None:
        return None

    gold_path = dataset_path / "gold"
    daily_file = gold_path / "gold_daily_cash_position.csv"
    monthly_file = gold_path / "gold_monthly_cash_flow.csv"

    if not daily_file.exists() or not monthly_file.exists():
        return None

    daily = pd.read_csv(daily_file, parse_dates=["date"])
    monthly = pd.read_csv(monthly_file)

    return daily, monthly


def render_cash_chart(daily: pd.DataFrame, monthly: pd.DataFrame):
    last_12_monthly = monthly.tail(12).copy()

    daily = daily.copy()
    daily["month"] = daily["date"].dt.strftime("%Y-%m")
    month_end_balance = (
        daily.groupby("month")["consolidated_cash_balance"].last().reset_index()
    )
    month_end_balance = month_end_balance[
        month_end_balance["month"].isin(last_12_monthly["month"])
    ]

    fig, ax1 = plt.subplots(figsize=(7.4, 3.5), dpi=150)
    fig.patch.set_alpha(0)
    ax1.set_facecolor("none")

    bar_colors = [
        "#3F7A5C" if v >= 0 else "#B23B2E"
        for v in last_12_monthly["net_cash_flow"]
    ]
    ax1.bar(
        last_12_monthly["month"],
        last_12_monthly["net_cash_flow"],
        color=bar_colors,
        width=0.55,
        alpha=0.88,
        zorder=2,
    )
    ax1.axhline(0, color="#C9A24B", linewidth=0.9, zorder=1)
    ax1.set_ylabel("Net cash flow (EUR)", fontsize=10, color="#3E4C63")
    ax1.tick_params(axis="x", rotation=45, labelsize=9, colors="#3E4C63")
    ax1.tick_params(axis="y", labelsize=9, colors="#3E4C63")
    for spine in ax1.spines.values():
        spine.set_visible(False)

    ax2 = ax1.twinx()
    ax2.plot(
        month_end_balance["month"],
        month_end_balance["consolidated_cash_balance"],
        color="#0A1B33",
        linewidth=2.4,
        marker="o",
        markersize=4,
        zorder=3,
    )
    ax2.set_ylabel("Closing balance (EUR)", fontsize=10, color="#0A1B33")
    ax2.tick_params(axis="y", labelsize=9, colors="#0A1B33")
    for spine in ax2.spines.values():
        spine.set_visible(False)

    fig.tight_layout()
    return fig


def compute_light_risk_signal(monthly: pd.DataFrame) -> tuple[str, str, str]:
    last_3 = monthly.tail(3)
    negative_count = int((last_3["net_cash_flow"] < 0).sum())

    if negative_count == 0:
        return (
            "Low",
            "sage",
            "No negative month in the last quarter.",
        )
    if negative_count == 1:
        return (
            "Medium",
            "amber",
            "1 of the last 3 months had negative net cash flow.",
        )
    return (
        "High",
        "coral",
        f"{negative_count} of the last 3 months had negative net cash flow.",
    )


# ============================================================
# NAVIGATION
# ============================================================

PAGES = [
    "Overview",
    "Transactions",
    "Invoices & OCR",
    "Cash-Flow Forecast",
    "Liquidity Risk",
    "What-if Simulator",
    "AI Financial Assistant",
]


# ============================================================
# CUSTOM CSS — premium / soft-luxury direction
# ============================================================
# Palette: warm ivory canvas, deep ink-navy sidebar, restrained
# champagne-gold accent, Fraunces for display type (financial
# report feel) over Inter body copy. The signature touch is the
# thin gold rule + left-edge gold hairline on every card, echoing
# the ring in the Treasoria mark.

st.markdown(
    """
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --ink: #0A1B33;
            --ink-soft: #3E4C63;
            --ivory: #FAF7F0;
            --card: #FFFFFF;
            --line: #E8E1D3;
            --gold: #C9A24B;
            --gold-soft: #E4CD94;
            --gold-bg: #F6EEDB;
            --sage: #3F7A5C;
            --sage-bg: #E7F1EA;
            --amber: #B8763A;
            --amber-bg: #F6E9D9;
            --slate: #5B6472;
        }

        html, body, [class*="css"], .stApp, .stApp * {
            font-size: 19px !important;
        }

        .stApp {
            background:
                radial-gradient(circle at top right, rgba(201,162,75,0.07), transparent 32%),
                var(--ivory);
            color: var(--ink);
        }

        /* Wider content area with slimmer side margins so the app
           fills a real monitor/projector instead of floating in a
           narrow column with dead space on both sides. */
        .block-container {
            max-width: 1720px;
            padding-top: 2.2rem;
            padding-bottom: 3rem;
            padding-left: 2.5rem;
            padding-right: 2.5rem;
        }

        h1, h2, h3, h4 {
            font-family: 'Fraunces', serif;
            color: var(--ink);
        }

        /* Title — deliberately NOT scoped under ".main": recent
           Streamlit versions don't reliably expose a ".main" class
           on the content container (they use data-testid instead),
           so ".main h1" was silently matching nothing and this
           title stayed at browser-default size no matter how large
           we set it here. There is no h1 in the sidebar in this
           app, so a bare "h1" selector is safe and guaranteed to
           match regardless of Streamlit's internal container
           naming in whatever version is deployed. */
        h1[data-testid="stHeading"], h1[data-testid="stHeading"] *,
        div[data-testid="stAppViewContainer"] h1,
        div[data-testid="stAppViewContainer"] h1 * {
            color: var(--ink) !important;
            font-family: 'Fraunces', serif !important;
            font-size: 46px !important;
            font-weight: 600 !important;
            letter-spacing: -0.01em;
        }

        /* General body copy inside the main content area — plain
           st.markdown / st.write text, captions, list items. Same
           reasoning as above: not scoped to ".main". */
        div[data-testid="stAppViewContainer"] p,
        div[data-testid="stAppViewContainer"] li,
        div[data-testid="stMarkdownContainer"] p,
        div[data-testid="stMarkdownContainer"] li {
            font-size: 18px !important;
            line-height: 1.6 !important;
        }

        [data-testid="stCaptionContainer"],
        [data-testid="stCaptionContainer"] * {
            font-size: 16px !important;
        }

        .treasoria-subtitle, .treasoria-subtitle * {
            color: var(--slate) !important;
            font-size: 21px !important;
            line-height: 1.65 !important;
            margin-top: 0.4rem;
            margin-bottom: 1.6rem;
        }

        .subtitle-hero {
            font-family: 'Fraunces', serif !important;
            font-style: italic;
            font-weight: 500;
            font-size: 28px !important;
            color: var(--ink) !important;
        }

        /* Company card — always visible, plain HTML inside the
           sidebar's own container so it reliably inherits the
           dark-navy background + white text already set on
           [data-testid="stSidebar"] * below. */
        .company-card {
            padding: 0.9rem 0.95rem 0.75rem;
            margin-bottom: 0.3rem;
            border: 1px solid rgba(201, 162, 75, 0.30);
            border-radius: 12px;
            background: rgba(255, 255, 255, 0.05);
            position: relative;
            overflow: hidden;
        }

        .company-card::before {
            content: "";
            position: absolute;
            top: 0; left: 0; right: 0; height: 3px;
            background: linear-gradient(90deg, var(--gold), var(--gold-soft), var(--gold));
        }

        .company-card-name {
            font-family: 'Fraunces', serif !important;
            font-size: 21px !important;
            font-weight: 600;
            color: #FFFFFF !important;
            margin-bottom: 0.35rem;
        }

        .company-card-owner {
            font-size: 16px !important;
            font-style: italic;
            color: #C7CEDE !important;
            margin-bottom: 0.4rem;
        }

        .company-card-address,
        .company-card-sector {
            font-size: 16px !important;
            color: #A9B6CC !important;
            line-height: 1.5 !important;
        }

        .company-card-sector { margin-top: 0.3rem; }

        .company-card-updated {
            display: block;
            font-size: 13px !important;
            color: #7C8BA8 !important;
            margin-top: 0.5rem;
            font-family: 'IBM Plex Mono', monospace;
            letter-spacing: 0.02em;
        }

        .gold-line {
            width: 100%;
            height: 2px;
            margin: 0.6rem 0 1.7rem 0;
            background: linear-gradient(90deg, var(--gold) 0%, var(--gold-soft) 45%, rgba(228,205,148,0) 100%);
        }

        /* ---------------- SIDEBAR ---------------- */
        [data-testid="stSidebar"] {
            background:
                radial-gradient(circle at 15% 0%, rgba(201,162,75,0.10), transparent 42%),
                linear-gradient(185deg, #0A1B33 0%, #0D2340 55%, #0A1B33 100%);
            border-right: 1px solid rgba(201, 162, 75, 0.35);
        }

        [data-testid="stSidebar"] * {
            color: #FFFFFF;
        }

        [data-testid="stSidebar"] img {
            display: block;
            max-height: 190px;
            margin: 0 auto;
            object-fit: contain;
            filter: drop-shadow(0 4px 14px rgba(201,162,75,0.25));
        }

        [data-testid="stSidebar"] hr {
            border-color: rgba(201, 162, 75, 0.28);
        }

        [data-testid="stSidebar"]
        div[role="radiogroup"] label {
            padding: 0.85rem 1rem;
            margin-bottom: 0.3rem;
            border-radius: 10px;
        }

        [data-testid="stSidebar"]
        div[role="radiogroup"] label,
        [data-testid="stSidebar"]
        div[role="radiogroup"] label * {
            font-size: 19px !important;
            font-weight: 500 !important;
        }

        [data-testid="stSidebar"]
        div[role="radiogroup"] label:hover {
            background-color: rgba(201, 162, 75, 0.12);
        }

        [data-testid="stSidebar"]
        div[role="radiogroup"] label:has(input:checked) {
            border-left: 2px solid var(--gold);
            background: linear-gradient(90deg, rgba(201,162,75,0.18), rgba(201,162,75,0.02));
        }

        [data-testid="stSidebar"] input[type="radio"] {
            display: none;
        }

        [data-testid="stSidebar"]
        [data-testid="stExpander"],
        [data-testid="stSidebar"]
        [data-testid="stExpander"] details,
        [data-testid="stSidebar"]
        [data-testid="stExpander"] summary,
        [data-testid="stSidebar"]
        [data-testid="stExpanderDetails"],
        [data-testid="stSidebar"]
        [data-testid="stForm"],
        [data-testid="stSidebar"]
        [data-testid="stVerticalBlockBorderWrapper"],
        [data-testid="stSidebar"]
        [data-testid="stExpander"] div {
            background-color: transparent !important;
            border-color: rgba(201, 162, 75, 0.28) !important;
            color: #E9ECF2 !important;
        }

        [data-testid="stSidebar"]
        [data-testid="stExpander"] {
            border: 1px solid rgba(201, 162, 75, 0.28) !important;
            border-radius: 10px !important;
        }

        [data-testid="stSidebar"]
        [data-testid="stExpander"] summary,
        [data-testid="stSidebar"]
        [data-testid="stExpander"] summary * {
            font-size: 16px !important;
        }

        [data-testid="stSidebar"]
        [data-testid="stForm"] {
            border: none !important;
            padding: 0.2rem 0.9rem 0.6rem !important;
        }

        [data-testid="stSidebar"]
        [data-testid="stForm"] label {
            color: #C7CEDE !important;
            font-size: 0.78rem;
        }

        [data-testid="stSidebar"]
        [data-testid="stForm"] input {
            background-color: rgba(10, 27, 51, 0.55) !important;
            color: #FFFFFF !important;
            border: 1px solid rgba(201, 162, 75, 0.35) !important;
            border-radius: 7px !important;
        }

        /* ---------------- CARDS ---------------- */
        .module-card {
            min-height: 240px;
            padding: 2.2rem;
            border: 1px solid var(--line);
            border-top: 3px solid var(--gold);
            border-radius: 16px;
            background: linear-gradient(160deg, #FFFFFF 0%, #FCFAF4 100%);
            box-shadow: 0 10px 26px rgba(10, 27, 51, 0.06);
        }

        .module-card h4, .module-card h4 * {
            margin: 0 0 1rem 0;
            font-size: 26px !important;
            color: var(--ink) !important;
        }

        .module-card p, .module-card p * {
            color: var(--slate) !important;
            font-size: 19px !important;
            line-height: 1.55 !important;
        }

        .status-ready {
            color: #1D5FA8 !important;
            font-weight: 750;
            font-size: 17px !important;
        }

        .status-planned {
            color: var(--amber) !important;
            font-weight: 750;
            font-size: 17px !important;
        }

        .assistant-intro {
            padding: 1rem 1.2rem;
            margin-bottom: 1rem;
            border-left: 4px solid var(--gold);
            border-radius: 0 12px 12px 0;
            background: linear-gradient(90deg, rgba(201,162,75,0.10), rgba(10,27,51,0.03));
            color: var(--ink);
            font-size: 1.05rem;
        }

        div[data-testid="stMetric"] {
            padding: 1.9rem 1.9rem;
            min-height: 128px;
            border: 1px solid var(--line);
            border-radius: 16px;
            background-color: var(--card);
            box-shadow: 0 10px 28px rgba(10, 27, 51, 0.05);
            position: relative;
            overflow: hidden;
        }

        div[data-testid="stMetric"]::before {
            content: "";
            position: absolute;
            top: 0; left: 0; width: 3px; height: 100%;
            background: linear-gradient(180deg, var(--gold), transparent);
        }

        div[data-testid="stMetricValue"], div[data-testid="stMetricValue"] * {
            font-family: 'Fraunces', serif !important;
            font-weight: 600 !important;
            color: var(--ink) !important;
            font-size: 48px !important;
            white-space: normal !important;
            overflow: visible !important;
            text-overflow: unset !important;
            line-height: 1.22 !important;
        }

        div[data-testid="stMetricLabel"], div[data-testid="stMetricLabel"] * {
            color: var(--slate) !important;
            font-size: 18px !important;
            font-weight: 600 !important;
        }

        .stButton > button {
            border: 1px solid var(--gold);
            border-radius: 9px;
            background: linear-gradient(135deg, #0A1B33, #16345E);
            color: #FFFFFF;
            font-weight: 650;
        }

        .stButton > button:hover {
            border-color: var(--gold-soft);
            color: #FFFFFF;
            box-shadow: 0 6px 18px rgba(201, 162, 75, 0.28);
        }

        div[class*="st-key-feedback_"] {
            display: inline-block;
        }

        div[class*="st-key-feedback_"] button {
            background: transparent !important;
            border: 1px solid rgba(201, 162, 75, 0.35) !important;
            border-radius: 6px !important;
            padding: 0.05rem 0.45rem !important;
            min-height: 1.7rem !important;
            font-size: 0.85rem !important;
            font-weight: 400 !important;
            line-height: 1.2 !important;
            box-shadow: none !important;
        }

        div[class*="st-key-feedback_"] button:hover {
            background: rgba(201, 162, 75, 0.14) !important;
            border-color: var(--gold-soft) !important;
            box-shadow: none !important;
        }

        div[class*="st-key-feedback_"]
        button[kind="primary"] {
            background: rgba(201, 162, 75, 0.85) !important;
            border-color: var(--gold) !important;
            color: var(--ink) !important;
        }

        [data-testid="stChatMessage"] {
            margin-bottom: 0.8rem;
            border: 1px solid var(--line);
            border-radius: 14px;
            background-color: var(--card);
            box-shadow: 0 5px 15px rgba(10, 27, 51, 0.05);
        }

        /* Data quality badge trigger — soft pill button. Not
           scoped to ".main" (see note above on h1) — this is the
           only st.popover trigger in the app, so no sidebar
           conflict risk. */
        [data-testid="stPopover"] > button,
        [data-testid="stPopover"] > button * {
            border-radius: 30px !important;
            font-weight: 600 !important;
            font-size: 17px !important;
            box-shadow: none !important;
            padding-top: 0.5rem !important;
            padding-bottom: 0.5rem !important;
        }

        /* Popover CONTENT: Streamlit renders this in a floating
           layer that is not nested inside .main or the sidebar in
           the DOM, so color rules scoped to those containers never
           reach it — that's what made the panel show invisible
           (white-on-white) text before. Target it directly by
           testid, unscoped, with an explicit background and text
           color so it is legible no matter where it portals to. */
        div[data-testid="stPopoverBody"] {
            background-color: #FFFFFF !important;
            border: 1px solid var(--line) !important;
            border-radius: 12px !important;
            box-shadow: 0 16px 40px rgba(10, 27, 51, 0.18) !important;
            z-index: 9999 !important;
            min-width: 340px !important;
        }

        div[data-testid="stPopoverBody"] * {
            color: var(--ink) !important;
            font-size: 16px !important;
            line-height: 1.6 !important;
        }

        .main div[data-testid="stExpander"] {
            border: 1px solid var(--line);
            border-left: 3px solid var(--gold);
            background-color: var(--card);
        }

        .section-title, .section-title * {
            font-family: 'Fraunces', serif !important;
            font-size: 30px !important;
            font-weight: 600 !important;
            color: var(--ink) !important;
            margin: 0.4rem 0 1.1rem;
        }

        .workflow-card {
            border: 1px solid var(--line);
            border-radius: 14px;
            background: var(--card);
            box-shadow: 0 10px 28px rgba(10, 27, 51, 0.05);
            padding: 0.4rem 1.8rem;
            margin-bottom: 1rem;
        }

        .workflow-row {
            display: flex;
            align-items: center;
            gap: 1.1rem;
            padding: 1.15rem 0;
            border-bottom: 1px solid #F1ECDE;
        }

        .workflow-row:last-child {
            border-bottom: none;
        }

        .workflow-num {
            font-family: 'IBM Plex Mono', monospace !important;
            font-size: 17px !important;
            font-weight: 600;
            color: var(--gold);
            background: var(--gold-bg);
            width: 2.6rem;
            height: 2.6rem;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
        }

        .workflow-text {
            font-size: 19px !important;
            color: var(--ink-soft) !important;
        }

        /* Latest Risk Signal card — three tones, same shape as the
           Data Quality badge palette (sage/amber/coral) so the
           whole app reads from one consistent risk vocabulary. */
        .risk-signal-card {
            border-radius: 14px;
            padding: 28px 24px;
            text-align: center;
            box-shadow: 0 10px 28px rgba(10, 27, 51, 0.05);
        }

        .risk-signal-level {
            font-family: 'Fraunces', serif;
            font-size: 34px;
            font-weight: 700;
            margin-bottom: 8px;
        }

        .risk-signal-reason {
            font-size: 15px;
            line-height: 1.4;
        }

        .risk-sage {
            background: var(--sage-bg);
            border: 1px solid #CFE3D6;
        }
        .risk-sage .risk-signal-level { color: var(--sage); }
        .risk-sage .risk-signal-reason { color: #2F5C46; }

        .risk-amber {
            background: var(--gold-bg);
            border: 1px solid #EAD8AE;
        }
        .risk-amber .risk-signal-level { color: #8A6115; }
        .risk-amber .risk-signal-reason { color: #6B4D14; }

        .risk-coral {
            background: #F7E4E0;
            border: 1px solid #E9C1B7;
        }
        .risk-coral .risk-signal-level { color: #A34632; }
        .risk-coral .risk-signal-reason { color: #7C3524; }

        .footer-text {
            margin-top: 2rem;
            color: #B7AE97;
            text-align: center;
            font-size: 0.72rem;
            letter-spacing: 0.16em;
            font-family: 'IBM Plex Mono', monospace;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SHARED HELPERS
# ============================================================

def render_placeholder_page(
    icon: str,
    title: str,
    description: str,
    bullet_points: list[str] | None = None,
) -> None:
    """
    Render a consistent placeholder layout for modules not yet
    connected.
    """

    st.title(f"{icon} {title}")
    st.markdown('<div class="gold-line"></div>', unsafe_allow_html=True)
    st.info(description)

    if bullet_points:
        st.markdown(
            "Planned indicators / fields:\n\n"
            + "\n".join(f"- {point};" for point in bullet_points)
        )


def render_feedback(message_index: int) -> None:
    """
    Render thumbs-up / thumbs-down feedback.
    """

    key = f"feedback_{message_index}"
    current_vote = st.session_state.get(key)

    col_up, col_down, _ = st.columns([1, 1, 10])

    with col_up:
        if st.button(
            "👍",
            key=f"{key}_up",
            type="primary" if current_vote == "up" else "secondary",
        ):
            st.session_state[key] = None if current_vote == "up" else "up"
            st.rerun()

    with col_down:
        if st.button(
            "👎",
            key=f"{key}_down",
            type="primary" if current_vote == "down" else "secondary",
        ):
            st.session_state[key] = None if current_vote == "down" else "down"
            st.rerun()


# ============================================================
# MODEL LOADING
# ============================================================

@st.cache_resource(show_spinner=False)
def load_models():
    """
    Load and cache the LLM and embedding model.
    """

    llm = initialise_llm()
    embed_model = get_embedding_model()

    return llm, embed_model


def initialise_chat_engine():
    """
    Create a new RAG chat engine with fresh conversation memory.
    """

    llm, embed_model = load_models()

    return get_chat_engine(llm=llm, embed_model=embed_model)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.image("assets/treasoria_logo.png", width="stretch")

    st.markdown(
        """
        <p style="
            margin-top:-1rem;
            text-align:center;
            color:#E4CD94;
            font-size:0.68rem;
            letter-spacing:0.14em;
        ">
            PREDICT. EXPLAIN. SIMULATE. DECIDE.
        </p>
        """,
        unsafe_allow_html=True,
    )

    st.divider()

    # Company identity is always visible in the sidebar — no click
    # required. This is plain HTML rendered inside the sidebar's own
    # dark-navy container, so it always inherits the correct white
    # text color (unlike a Streamlit popover, whose content portals
    # outside the sidebar's DOM and does not inherit this styling —
    # that's what caused white-on-white invisible text before).
    st.markdown(
        f"""
        <div class="company-card">
            <div class="company-card-name">{ACTIVE_COMPANY['name']}</div>
            <div class="company-card-owner">Owner: {ACTIVE_COMPANY['owner']}</div>
            <div class="company-card-address">
                {ACTIVE_COMPANY['address']}<br>{ACTIVE_COMPANY['city']}
            </div>
            <div class="company-card-sector">{ACTIVE_COMPANY['sector']}</div>
            <div class="company-card-updated">
                Last online: {ACTIVE_COMPANY['last_updated']}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.divider()

    selected_page = st.radio(
        "Navigation",
        options=PAGES,
        label_visibility="collapsed",
    )

    st.divider()

    # Always collapsed: editing is one click away, but nobody needs
    # the input fields staring at them by default — including on
    # first run, when the profile is still empty.
    with st.expander("✏️ Edit company profile", expanded=False):

        with st.form("company_profile_form"):

            new_name = st.text_input(
                "Café name",
                value=ACTIVE_COMPANY["name"],
                placeholder="e.g. Code & Coffee GmbH",
            )

            new_address = st.text_input(
                "Address (street)",
                value=ACTIVE_COMPANY["address"],
                placeholder="e.g. Ravensberger Str. 22",
            )

            new_city = st.text_input(
                "City / Country",
                value=ACTIVE_COMPANY["city"],
                placeholder="e.g. 33602 Bielefeld, Germany",
            )

            new_owner = st.text_input(
                "Owner name",
                value=ACTIVE_COMPANY["owner"],
                placeholder="e.g. Blue Jesus",
            )

            new_sector = st.text_input(
                "Sector",
                value=ACTIVE_COMPANY["sector"],
                placeholder="e.g. International Café & Gastronomy",
            )

            submitted = st.form_submit_button("Save", width="stretch")

            if submitted:
                st.session_state.company_profile.update(
                    {
                        "name": new_name,
                        "owner": new_owner,
                        "address": new_address,
                        "city": new_city,
                        "sector": new_sector,
                    }
                )

                save_company(st.session_state.company_profile)

                st.success("Company profile updated.")
                st.rerun()


# ============================================================
# OVERVIEW PAGE
# ============================================================

if selected_page == "Overview":

    st.title("Treasoria Overview")

    st.markdown(
        f"""
        <p class="treasoria-subtitle">
            <span class="subtitle-hero">See Tomorrow's Cash. Make Better Decisions Today.</span><br>
            Financial intelligence for {ACTIVE_COMPANY["name"]}
        </p>
        """,
        unsafe_allow_html=True,
    )

    st.markdown('<div class="gold-line"></div>', unsafe_allow_html=True)

    render_data_quality_badge()

    st.write("")

    try:
        kpi_summary = load_kpi_summary()

        def get_kpi(kpi_name: str) -> str:
            return kpi_summary.get(kpi_name, "Not available")

        def split_parenthetical(raw: str) -> tuple[str, str | None]:
            """
            Some KPI values from the Gold layer are a full sentence with
            a parenthetical detail, e.g. "Not burning cash (positive
            3-month average net flow)". Splitting it lets the metric
            card show a short headline value with the detail underneath
            as a caption, instead of cramming a whole sentence into the
            big metric number. Falls through untouched for KPIs that
            don't have this shape.
            """

            if "(" in raw and raw.rstrip().endswith(")"):
                idx = raw.index("(")
                main = raw[:idx].strip()
                sub = raw[idx + 1: raw.rindex(")")].strip()
                if main:
                    return main, sub
            return raw, None

        kpi_column_1, kpi_column_2, kpi_column_3 = st.columns(3)

        with kpi_column_1:
            st.metric(
                label="Closing cash balance",
                value=get_kpi("Consolidated Cash Balance (end of period)"),
                help=(
                    "Consolidated closing balance of the main and "
                    "secondary bank accounts."
                ),
            )

        with kpi_column_2:
            st.metric(
                label="Average monthly net cash flow",
                value=get_kpi("Average Monthly Net Cash Flow"),
                help=(
                    "Average monthly difference between external "
                    "cash inflows and outflows."
                ),
            )

        with kpi_column_3:
            st.metric(
                label="Total cash in",
                value=get_kpi("Cash-Collected Revenue (24 months)"),
                help=(
                    "Total retail and B2B cash collected during the "
                    "represented period — not all of it is "
                    "necessarily recognized revenue."
                ),
            )

        kpi_column_4, kpi_column_5, kpi_column_6 = st.columns(3)

        with kpi_column_4:
            st.metric(
                label="Open customer receivables",
                value=get_kpi("Open Receivables"),
                help="Customer invoices that remain unpaid.",
            )

        with kpi_column_5:
            st.metric(
                label="Closing credit-card debt",
                value=get_kpi("Credit Card Debt (end of period)"),
                help="Outstanding credit-card liability at the end of the period.",
            )

        with kpi_column_6:
            runway_main, runway_sub = split_parenthetical(get_kpi("Runway"))
            st.metric(
                label="Cash runway",
                value=runway_main,
                help="Estimated operating runway based on the current cash-flow profile.",
            )
            if runway_sub:
                st.caption(runway_sub)

        st.caption("Financial results calculated by the Treasoria Gold data pipeline.")

    except (FileNotFoundError, ValueError, pd.errors.ParserError) as error:
        st.error("The financial KPI summary could not be loaded.")
        st.code(str(error), language="text")

    # --------------------------------------------------------
    # CASH POSITION CHART + LATEST RISK SIGNAL
    # --------------------------------------------------------

    chart_data = load_cash_position_chart_data()

    if chart_data is not None:
        daily_df, monthly_df = chart_data

        chart_col, risk_col = st.columns([2, 1])

        with chart_col:
            st.markdown(
                '<h2 class="section-title" style="font-size:22px !important;">'
                "Cash Position &amp; Monthly Net Cash Flow — Last 12 Months</h2>",
                unsafe_allow_html=True,
            )
            fig = render_cash_chart(daily_df, monthly_df)
            st.pyplot(fig, width="stretch")

        with risk_col:
            st.markdown(
                '<h2 class="section-title" style="font-size:22px !important;">'
                "Latest Risk Signal</h2>",
                unsafe_allow_html=True,
            )
            level, tone, reason = compute_light_risk_signal(monthly_df)
            st.markdown(
                f"""
                <div class="risk-signal-card risk-{tone}">
                    <div class="risk-signal-level">{level}</div>
                    <div class="risk-signal-reason">{reason}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.caption(
                "Lightweight signal from the last 3 months of real "
                "data — the full 6-rule Liquidity Risk engine is a "
                "separate page, still to come."
            )

    st.markdown(
        '<h2 class="section-title">Treasoria Modules</h2>',
        unsafe_allow_html=True,
    )

    column_1, column_2, column_3 = st.columns(3)

    with column_1:
        st.markdown(
            """
            <div class="module-card">
                <h4>📄 Documents & OCR</h4>
                <p>
                    Extract and validate invoice and
                    financial-document information.
                </p>
                <p class="status-planned">
                    Integration planned
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with column_2:
        st.markdown(
            """
            <div class="module-card">
                <h4>📈 Forecast &amp; Risk Intelligence</h4>
                <p>
                    Financial KPIs generated from the
                    validated Gold analytical tables.
                </p>
                <p class="status-ready">
                    Connected
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with column_3:
        st.markdown(
            """
            <div class="module-card">
                <h4>✨ AI Financial Assistant</h4>
                <p>
                    Structured financial answers and
                    contextual explanations powered by
                    SQLite and RAG.
                </p>
                <p class="status-ready">
                    Ready
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown(
        '<h2 class="section-title">Decision-Intelligence Workflow</h2>',
        unsafe_allow_html=True,
    )

    workflow_steps = [
        "Extract financial information using OCR.",
        "Validate, clean and transform the extracted data.",
        "Store trusted financial information.",
        "Calculate financial KPIs.",
        "Forecast future cash positions.",
        "Identify potential liquidity risks.",
        "Simulate alternative business scenarios.",
        "Explain results through the financial assistant.",
    ]

    # No leading whitespace / newlines in the per-row HTML: Markdown
    # treats a line indented 4+ spaces after a blank line as a code
    # block, and the row-by-row join() below produces exactly that
    # blank-line-then-indented pattern if the template isn't kept
    # flush-left on a single line — that's what showed raw HTML
    # tags on screen for every row after the first one.
    workflow_html = "".join(
        f'<div class="workflow-row"><div class="workflow-num">{i:02d}</div><div class="workflow-text">{step}</div></div>'
        for i, step in enumerate(workflow_steps, start=1)
    )

    st.markdown(
        f'<div class="workflow-card">{workflow_html}</div>',
        unsafe_allow_html=True,
    )


# ============================================================
# TRANSACTIONS PAGE
# ============================================================

elif selected_page == "Transactions":

    render_placeholder_page(
        icon="📋",
        title="Transactions",
        description=(
            "This page will show the full filterable transaction "
            "ledger once the Silver layer is connected."
        ),
        bullet_points=[
            "date, amount, category, counterparty, flow type",
            "bank account and transaction source",
            "reconciliation status",
            "internal vs. external flag",
            "category breakdown",
            "CSV export of the active filter",
        ],
    )


# ============================================================
# INVOICES & OCR PAGE
# ============================================================

elif selected_page == "Invoices & OCR":

    st.title("📄 Invoices & OCR")
    st.markdown('<div class="gold-line"></div>', unsafe_allow_html=True)

    st.info(
        "This module will extract fields from invoices and "
        "financial documents before sending validated data to "
        "the ETL pipeline."
    )

    st.file_uploader(
        "Upload a financial document",
        type=["pdf", "png", "jpg", "jpeg"],
        disabled=True,
    )

    st.caption("Document upload is disabled until the OCR pipeline is connected.")


# ============================================================
# FORECAST PAGE
# ============================================================

elif selected_page == "Cash-Flow Forecast":

    render_placeholder_page(
        icon="📈",
        title="Cash-Flow Forecast",
        description=(
            "Historical cash flow, forecasts, confidence intervals "
            "and model comparison will appear here once the "
            "forecasting module is connected."
        ),
        bullet_points=[
            "30/60/90-day forecast",
            "confidence intervals",
            "actual vs. forecast comparison",
            "model comparison",
            "MAE / RMSE / MAPE",
        ],
    )


# ============================================================
# LIQUIDITY RISK PAGE
# ============================================================

elif selected_page == "Liquidity Risk":

    render_placeholder_page(
        icon="⚠️",
        title="Liquidity Risk",
        description=(
            "Risk periods, overdue invoices and suggested actions "
            "will appear here once the risk engine is connected."
        ),
        bullet_points=[
            "projected negative cash",
            "large upcoming payments",
            "overdue client collections",
            "low cash balance alerts",
            "short runway alerts",
            "exceptional outflows",
            "negative cash-flow trend",
            "high forecast uncertainty",
            "customer concentration risk",
        ],
    )


# ============================================================
# WHAT-IF SIMULATOR PAGE
# ============================================================

elif selected_page == "What-if Simulator":

    render_placeholder_page(
        icon="🧮",
        title="What-if Simulator",
        description=(
            "Users will be able to simulate delayed payments, "
            "expense increases, new hires and other scenarios once "
            "this module is connected."
        ),
        bullet_points=[
            "reference scenario",
            "modified scenario",
            "projected final balance",
            "minimum projected balance",
            "low-point date",
            "days below critical threshold",
            "save scenarios",
            "compare scenarios",
            "export scenarios",
        ],
    )


# ============================================================
# AI FINANCIAL ASSISTANT PAGE
# ============================================================

elif selected_page == "AI Financial Assistant":

    if "messages" not in st.session_state:
        st.session_state.messages = []

    if "chat_engine" not in st.session_state:
        with st.spinner("Initialising the Treasoria assistant..."):
            st.session_state.chat_engine = initialise_chat_engine()

    title_column, button_column = st.columns([4, 1], vertical_alignment="center")

    with title_column:
        st.title("✨ AI Financial Assistant")
        st.caption(
            "Precise financial answers from structured data and "
            "validated Treasoria documentation."
        )

    with button_column:
        if st.button("＋ New Chat", width="stretch"):
            st.session_state.messages = []

            with st.spinner("Starting a new conversation..."):
                st.session_state.chat_engine = initialise_chat_engine()

            st.rerun()

    st.markdown(
        """
        <div class="assistant-intro">
            Ask Treasoria about cash balances, cash flow, invoices,
            receivables, payment behaviour, accounting controls or
            financial events.
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.caption(
        "This assistant combines Treasoria's structured financial "
        "data with validated documentation to provide precise "
        "financial answers and contextual explanations."
    )

    for message_index, message in enumerate(st.session_state.messages):

        with st.chat_message(message["role"]):
            st.markdown(message["content"])

            if message["role"] == "assistant":
                render_feedback(message_index)

    user_question = st.chat_input("Ask a financial question about Treasoria...")

    if user_question:

        st.session_state.messages.append(
            {"role": "user", "content": user_question}
        )

        with st.chat_message("user"):
            st.markdown(user_question)

        with st.chat_message("assistant"):

            try:
                response_start = time.perf_counter()

                with st.spinner("Analysing your financial question..."):

                    # ====================================================
                    # HYBRID SQL + RAG ROUTING
                    # ====================================================

                    sql_response = answer_sql_question(user_question)

                    if sql_response is not None:
                        # Exact structured result returned from SQLite.
                        response = sql_response
                        response_text = str(response)
                        sources = []

                    else:
                        # No structured SQL intent matched. Fall back to
                        # the RAG engine.
                        response = st.session_state.chat_engine.chat(user_question)
                        response_text = str(response)
                        sources = []

                        for source_node in getattr(response, "source_nodes", []):
                            metadata = source_node.node.metadata or {}

                            source_name = (
                                metadata.get("file_name")
                                or metadata.get("filename")
                                or metadata.get("file_path")
                                or "Treasoria document"
                            )

                            sources.append(
                                {
                                    "name": str(source_name),
                                    "text": source_node.node.get_content(),
                                    "score": source_node.score,
                                }
                            )

                response_time = time.perf_counter() - response_start

                st.markdown(response_text)

                st.session_state.messages.append(
                    {
                        "role": "assistant",
                        "content": response_text,
                        "response_time": response_time,
                        "sources": sources,
                    }
                )

                render_feedback(len(st.session_state.messages) - 1)

            except Exception as error:
                st.error(
                    "Treasoria could not generate a response. "
                    "Please try again."
                )
                st.exception(error)


# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
    <p class="footer-text">
        TREASORIA · PREDICT · EXPLAIN · SIMULATE · DECIDE
    </p>
    """,
    unsafe_allow_html=True,
)